// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaQ7wJJXji8MC9BcChnWKQUAOYSkFV1Fs',
    appId: '1:764224566319:web:23b04a24b64783615542da',
    messagingSenderId: '764224566319',
    projectId: 'appnotification-444bd',
    authDomain: 'appnotification-444bd.firebaseapp.com',
    storageBucket: 'appnotification-444bd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChjIgwlaJ0KcmS1X9JXzivJ12XMrDdRhs',
    appId: '1:764224566319:android:aaa41a3250fe8e9c5542da',
    messagingSenderId: '764224566319',
    projectId: 'appnotification-444bd',
    storageBucket: 'appnotification-444bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_CTAi7chMk_pm4PLhkfCA5FfvcsNUJ3Q',
    appId: '1:764224566319:ios:e44dd0dc3c94d7db5542da',
    messagingSenderId: '764224566319',
    projectId: 'appnotification-444bd',
    storageBucket: 'appnotification-444bd.firebasestorage.app',
    iosBundleId: 'com.example.appnotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_CTAi7chMk_pm4PLhkfCA5FfvcsNUJ3Q',
    appId: '1:764224566319:ios:e44dd0dc3c94d7db5542da',
    messagingSenderId: '764224566319',
    projectId: 'appnotification-444bd',
    storageBucket: 'appnotification-444bd.firebasestorage.app',
    iosBundleId: 'com.example.appnotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaQ7wJJXji8MC9BcChnWKQUAOYSkFV1Fs',
    appId: '1:764224566319:web:05089705e320213e5542da',
    messagingSenderId: '764224566319',
    projectId: 'appnotification-444bd',
    authDomain: 'appnotification-444bd.firebaseapp.com',
    storageBucket: 'appnotification-444bd.firebasestorage.app',
  );
}
